services:
- type: web
  name: sageapp # Replace with your service's name
  env: static
  buildCommand: npm run build  # Your build command
  staticPublishPath: ./build  # Directory where your static files are located
  routes:
    - type: rewrite
      source: /**
      destination: /index.html
